In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

In [2]:
df= pd.read_csv("Dataset.csv")
df

                                           selected_text  sentiment
0                           have responded if were going          0
1                                               sooo sad          1
2                                            bullying me          1
3                                         leave me alone          1
4                                                sons of          1
...                                                  ...        ...
27476                                               lost          1
27477                                          don force          1
27478                           yay good for both of you          2
27479                                but it was worth it          2
27480  all this flirting going on the atg smiles yay ...          0

[27481 rows x 2 columns]

In [5]:
df.isnull().sum()

selected_text    0
sentiment        0
dtype: int64

In [4]:
df = df.dropna()

In [6]:
df.head()

                  selected_text  sentiment
0  have responded if were going          0
1                      sooo sad          1
2                   bullying me          1
3                leave me alone          1
4                       sons of          1

In [7]:
def clean_text(text):
    return text.lower()
df['clean_text'] = df['selected_text'].apply(clean_text)

print(df[['selected_text', 'clean_text']].head())

                  selected_text                    clean_text
0  have responded if were going  have responded if were going
1                      sooo sad                      sooo sad
2                   bullying me                   bullying me
3                leave me alone                leave me alone
4                       sons of                       sons of

/var/folders/s7/3cn6dv69701dkpcp4c414khw0000gn/T/ipykernel_92759/154726496.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['clean_text'] = df['selected_text'].apply(clean_text)

In [8]:
df.head()

                  selected_text  sentiment                    clean_text
0  have responded if were going          0  have responded if were going
1                      sooo sad          1                      sooo sad
2                   bullying me          1                   bullying me
3                leave me alone          1                leave me alone
4                       sons of          1                       sons of

In [19]:
X_train,X_test,y_train,y_test = train_test_split(df['clean_text'],df['sentiment'],test_size=0.2, random_state=42)
X_test.head()

11105                                        holiday again
18798                                       feel so stupid
5283     night out had put on hold weeks coz was so ill...
8968                                                  glad
6097                              on maxim magazine hot of
Name: clean_text, dtype: object

In [20]:
vectorizer = TfidfVectorizer(max_features=5000,ngram_range=(1,2))
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print("TF-IDF shape (train):", X_train_tfidf.shape)
print("TF-IDF shape (test):", X_test_tfidf.shape)

TF-IDF shape (train): (21877, 5000)
TF-IDF shape (test): (5470, 5000)

In [22]:
bnb = BernoulliNB()
bnb.fit(X_train_tfidf,y_train)
pred = bnb.predict(X_test_tfidf)

print(f"accuracy of bnb:{accuracy_score(y_test,pred)}")
print(f"classification report:{classification_report(y_test,pred)}")

accuracy of bnb:0.759963436928702
classification report:              precision    recall  f1-score   support

           0       0.83      0.72      0.77      2232
           1       0.73      0.70      0.71      1557
           2       0.72      0.87      0.79      1681

    accuracy                           0.76      5470
   macro avg       0.76      0.76      0.76      5470
weighted avg       0.77      0.76      0.76      5470

In [23]:
svm = LinearSVC()
svm.fit(X_train_tfidf,y_train)
pred_svm = svm.predict(X_test_tfidf)


print(f"accuracy of bnb:{accuracy_score(y_test,pred_svm)}")
print(f"classification report:{classification_report(y_test,pred_svm)}")

accuracy of bnb:0.8082266910420476
classification report:              precision    recall  f1-score   support

           0       0.79      0.85      0.82      2232
           1       0.78      0.76      0.77      1557
           2       0.86      0.79      0.82      1681

    accuracy                           0.81      5470
   macro avg       0.81      0.80      0.81      5470
weighted avg       0.81      0.81      0.81      5470

In [24]:
LR = LogisticRegression()
LR.fit(X_train_tfidf,y_train)
pred_lr = LR.predict(X_test_tfidf)


print(f"accuracy of bnb:{accuracy_score(y_test,pred_lr)}")
print(f"classification report:{classification_report(y_test,pred_lr)}")

accuracy of bnb:0.8201096892138939
classification report:              precision    recall  f1-score   support

           0       0.79      0.89      0.84      2232
           1       0.79      0.77      0.78      1557
           2       0.90      0.78      0.84      1681

    accuracy                           0.82      5470
   macro avg       0.83      0.81      0.82      5470
weighted avg       0.82      0.82      0.82      5470

In [32]:
# making perdictions
sample_tweets = ["I love this!", "I hate that!", "It was okay, not great.","neutral"]
vectorize_sample = vectorizer.transform(sample_tweets)

print("prediction on sample tweet\n")
print(f"bnb :{bnb.predict(vectorize_sample)}")
print(f"svm : {svm.predict(vectorize_sample)}")
print(f"lr : {LR.predict(vectorize_sample)}")

prediction on sample tweet

bnb :[2 1 2 2]
svm : [2 1 2 1]
lr : [2 1 2 1]

In [33]:
import pickle

In [35]:
file_path = "senti_model_01.pkl"
with open(file_path, "wb") as file:
    pickle.dump(LR, file)

In [ ]:
file_path = "senti_model_01_svm.pkl"
with open(file_path, "wb") as file:
    pickle.dump(sv, file)